// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDebFdu8vSZF7gvBO-ErC-0Elchf8Uow',
    appId: '1:1045149251295:web:06f10de7275a760291db6a',
    messagingSenderId: '1045149251295',
    projectId: 'customerinterviewapp',
    authDomain: 'customerinterviewapp.firebaseapp.com',
    storageBucket: 'customerinterviewapp.firebasestorage.app',
    measurementId: 'G-R5MJ3KYLPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcPI2NbvzLLYbdo7DZIsPYsMLnBpDMyY',
    appId: '1:1045149251295:android:3523516cee95b68591db6a',
    messagingSenderId: '1045149251295',
    projectId: 'customerinterviewapp',
    storageBucket: 'customerinterviewapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFirIvVT1ppbqZZL7krxvXQdi1glhOgP4',
    appId: '1:1045149251295:ios:d7dcaeb17d3b2ded91db6a',
    messagingSenderId: '1045149251295',
    projectId: 'customerinterviewapp',
    storageBucket: 'customerinterviewapp.firebasestorage.app',
    iosClientId: '1045149251295-fj0hf6s5cisk4b8ievqtk8vc3lohc1la.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseFlutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFirIvVT1ppbqZZL7krxvXQdi1glhOgP4',
    appId: '1:1045149251295:ios:d7dcaeb17d3b2ded91db6a',
    messagingSenderId: '1045149251295',
    projectId: 'customerinterviewapp',
    storageBucket: 'customerinterviewapp.firebasestorage.app',
    iosClientId: '1045149251295-fj0hf6s5cisk4b8ievqtk8vc3lohc1la.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseFlutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcDebFdu8vSZF7gvBO-ErC-0Elchf8Uow',
    appId: '1:1045149251295:web:74e58cf0db3a80f091db6a',
    messagingSenderId: '1045149251295',
    projectId: 'customerinterviewapp',
    authDomain: 'customerinterviewapp.firebaseapp.com',
    storageBucket: 'customerinterviewapp.firebasestorage.app',
    measurementId: 'G-X7VBCVJKE8',
  );
}
