// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVeUuZEmZ0bPrqqCYeongF2Ee4g2LReI',
    appId: '1:465931274801:web:04ad3f5e25e0c7206f6310',
    messagingSenderId: '465931274801',
    projectId: 'fintally',
    authDomain: 'fintally.firebaseapp.com',
    storageBucket: 'fintally.firebasestorage.app',
    measurementId: 'G-3L8E3PCDSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYcHicj35gSn3mPJJkTB9h4-Alny_XYI',
    appId: '1:465931274801:android:d7e28e0c6e7ebae66f6310',
    messagingSenderId: '465931274801',
    projectId: 'fintally',
    storageBucket: 'fintally.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwFL-wjjSORM6U97qSL9s1Mj6Ca_8-Ss',
    appId: '1:465931274801:ios:334b0125245730126f6310',
    messagingSenderId: '465931274801',
    projectId: 'fintally',
    storageBucket: 'fintally.firebasestorage.app',
    iosBundleId: 'com.codegriha.fintally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwFL-wjjSORM6U97qSL9s1Mj6Ca_8-Ss',
    appId: '1:465931274801:ios:3a0c2e41d869850d6f6310',
    messagingSenderId: '465931274801',
    projectId: 'fintally',
    storageBucket: 'fintally.firebasestorage.app',
    iosBundleId: 'com.codegriha.fintally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVVeUuZEmZ0bPrqqCYeongF2Ee4g2LReI',
    appId: '1:465931274801:web:c0b83522dbf3243c6f6310',
    messagingSenderId: '465931274801',
    projectId: 'fintally',
    authDomain: 'fintally.firebaseapp.com',
    storageBucket: 'fintally.firebasestorage.app',
    measurementId: 'G-YHMGNRKEG8',
  );

}